### ISSUE TITLE
Error no connection to printer

### ISSUE THREAD

**Issue by Seelenkind** [colinrgodsey/step-daemon#15]
whats wrong here, what have to do ? installed at octoprint

Changing monitoring state from "Opening serial connection" to "Error: Connection error, see Terminal tab"
Changing monitoring state from "Error: Connection error, see Terminal tab" to "Offline (Error: Connection error, see Terminal tab)"
Unexpected error while connecting to serial port /dev/ttyACM0, baudrate 115200 from hook stepd: Exception: 'Step Daemon is still updating.' @ comm.py:_open_serial:3670

**Comment by tiagofreire-pt** [comment]
Same issue here:

```
Connecting to Step Daemon
Unexpected error while connecting to serial port /dev/ttyUSB0, baudrate 115200 from hook stepd: FileNotFoundError: '[Errno 2] No such file or directory: '/home/pi/.octoprint/data/stepd/stepd': '/home/pi/.octoprint/data/stepd/stepd'' @ comm.py:_open_serial:3670
Could not open port /dev/ttyUSB0, baudrate 115200, skipping
Changing monitoring state from "Detecting serial connection" to "Error: No more candidates to test, and no working port/baudrate combination detected."
Changing monitoring state from "Error: No more candidates to test, and no working port/baudrate combination detected." to "Offline (Error: No more candidates to test, and no working port/baudrate combination detected.)"
```

**Comment by Psyobilin** [comment]
Here too!

> Changing monitoring state from "Offline" to "Opening serial connection"
> Connecting to Step Daemon
> Changing monitoring state from "Opening serial connection" to "Error: Connection error, see Terminal tab"
> Changing monitoring state from "Error: Connection error, see Terminal tab" to "Offline (Error: Connection error, see Terminal tab)"
> Unexpected error while connecting to serial port /dev/ttyACM0, baudrate 250000 from hook stepd: FileNotFoundError: '[Errno 2] No such file or directory: '/home/openhabian/.octoprint/data/stepd/stepd': '/home/openhabian/.octoprint/data/stepd/stepd'' @ comm.py:_open_serial:3670

I uninstalled StepD and it is still shown under Plugins. I think that there is the problem. But I don´t know where to get rid of it.

**Comment by Psyobilin** [comment]
I deleted my .octoprint folder and gave it a fresh start. that solved the problem for me.

**Comment by bwiedmann** [comment]
`/home/pi/.octoprint/data/stepd/stepd` seems to be missing.

Is golang installed on your Pi? 

You can install it with

`sudo apt install golang`

If the golang package was missing, uninstall the StepD plugin, clean data and reinstall again for it to rebuild the binary.

**Comment by Amilleriiw** [comment]
so trying to set this up i have run into some walls anyone know what to do im not 100% code/pi savvy  rpi 4 b anyone that can help that would be awesome thanks

pi@octopi:~ $ sudo apt install golang
[sudo] password for pi:
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  golang-1.11 golang-1.11-doc golang-1.11-go golang-1.11-src golang-doc golang-go golang-src
Suggested packages:
  bzr | brz mercurial
The following NEW packages will be installed:
  golang golang-1.11 golang-1.11-doc golang-1.11-go golang-1.11-src golang-doc golang-go golang-src
0 upgraded, 8 newly installed, 0 to remove and 45 not upgraded.
Need to get 51.8 MB/51.9 MB of archives.
After this operation, 258 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 http://raspbian.raspberrypi.org/raspbian buster/main armhf golang-1.11-src armhf 1.11.6-1+rpi1+deb10u2
  404  Not Found [IP: 93.93.128.193 80]
Err:2 http://raspbian.raspberrypi.org/raspbian buster/main armhf golang-1.11-go armhf 1.11.6-1+rpi1+deb10u2
  404  Not Found [IP: 93.93.128.193 80]
Err:3 http://raspbian.raspberrypi.org/raspbian buster/main armhf golang-1.11-doc all 1.11.6-1+rpi1+deb10u2
  404  Not Found [IP: 93.93.128.193 80]
Err:4 http://raspbian.raspberrypi.org/raspbian buster/main armhf golang-1.11 all 1.11.6-1+rpi1+deb10u2
  404  Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/g/golang-1.11/golang-1.11-src_1.11.6-1+rpi1+deb10u2_armhf.deb  404  Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/g/golang-1.11/golang-1.11-go_1.11.6-1+rpi1+deb10u2_armhf.deb  404  Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/g/golang-1.11/golang-1.11-doc_1.11.6-1+rpi1+deb10u2_all.deb  404  Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/g/golang-1.11/golang-1.11_1.11.6-1+rpi1+deb10u2_all.deb  404  Not Found [IP: 93.93.128.193 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
pi@octopi:~ $

**Comment by cosworth99** [comment]
Did a fresh install using pi imager. Installed Golang. Ran the zip file in the plugin installer. Did this twice. Still getting a ValueError: 'I/O operation on closed file' @ comm.py:_readline:3940 error as well.

Specifically:

Unexpected error while reading serial port, please consult octoprint.log for details: ValueError: 'I/O operation on closed file' @ comm.py:_readline:3940
Changing monitoring state from "Operational" to "Offline after error"
Connection closed, closing down monitor

It will connect, handshake/echo a reply from an M503 then pop out of connection.

Once I turn the StepDaemon plugin off, everything is fine. I see this is different from the first post here but it's related to a comm.py serial issue I believe. Maybe not stepD code, but code that it depended on that broke something in an update?
