### ISSUE TITLE
cannot download & install Octoprint plugin

### ISSUE THREAD

**Issue by toxicOne-SV01PRO** [colinrgodsey/step-daemon#2]
the download link is down ....!

**Comment by colinrgodsey** [comment]
Sorry, I still need to clean up some things on the plugin and get it appropriately packaged. Excited for the interest though! I should have it packaged up today, just have to find a better solution for the UI "updating" status.

**Comment by colinrgodsey** [comment]
@toxicOne-SV01PRO finally have a good beta version of the plugin going: https://raw.githubusercontent.com/colinrgodsey/maven/master/step-daemon/octoprint-plugin/latest.zip
