### ISSUE TITLE
What happened to the `rewrite` branch?

### ISSUE THREAD

**Issue by cab404** [colinrgodsey/step-daemon#8]
It suddenly disappeared without a trace :/

**Comment by PaulGD03** [comment]
It looks like it has been merged into master with this [commit](https://github.com/colinrgodsey/step-daemon/commit/45bcabef849baf87f799e54c7c203fd3f49dba56)

**Comment by cab404** [comment]
oh. The message was not updated in readme

**Comment by colinrgodsey** [comment]
sorry, did a big branch shuffle a few days ago. The go rewrite is pretty much where the scala version was now. Still doing some testing for cartesian devices, but seems right so far.
